version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana:/data
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    ports:
      - 1880:1880
    networks:
      - monitoring
    volumes:
      - nodered:/data
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb:/data
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Welcome1 
  # telegraf:
  #   image: telegraf
  #   container_name: telegraf
  #   restart: always
  #   extra_hosts:
  #    - "influxdb:192.168.0.110"
  #   environment:
  #     HOST_PROC: /rootfs/proc
  #     HOST_SYS: /rootfs/sys
  #     HOST_ETC: /rootfs/etc
  #   volumes:
  #    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - /sys:/rootfs/sys:ro
  #    - /proc:/rootfs/proc:ro
  #    - /etc:/rootfs/etc:ro
networks:
  monitoring:
volumes:
  nodered:
    external: true
  grafana:
    external: true
  influxdb:
    external: true